name: Deploy to Production

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    environment: production

    # Chỉ chạy deploy khi tất cả tests đã pass
    needs: []

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests before deploy
        run: |
          npm run lint
          npx tsc --noEmit
          npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Build Docker image
        run: |
          docker build -t chatstoryai:${{ github.sha }} .
          docker tag chatstoryai:${{ github.sha }} chatstoryai:latest

      # Uncomment và cấu hình theo nhu cầu deploy của bạn
      # - name: Deploy to server
      #   run: |
      #     echo "Deploy to production server"
      #     # Thêm commands deploy ở đây

      - name: Create deployment artifact
        run: |
          tar -czf deployment-${{ github.sha }}.tar.gz \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=.next \
            .

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-${{ github.sha }}
          path: deployment-${{ github.sha }}.tar.gz
          retention-days: 30

      - name: Notify deployment status
        run: |
          echo "Deployment completed successfully!"
          echo "SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
