name: Performance Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: "./.lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          NEXT_TELEMETRY_DISABLED: 1

  bundle-analysis:
    name: Bundle Size Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build application
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Analyze bundle size
        run: |
          echo "=== Bundle Size Analysis ==="
          echo "Build completed successfully!"

          if [ -d ".next" ]; then
            echo "✅ .next directory exists"
            ls -la .next/
          else
            echo "❌ .next directory not found"
            exit 1
          fi

          if [ -d ".next/static" ]; then
            echo "✅ Static files found"
            echo "=== JavaScript files ==="
            find .next/static -name "*.js" -exec ls -lh {} \; | head -10
            echo "=== Total static size ==="
            du -sh .next/static
          else
            echo "❌ No static files found"
          fi
